sonar.projectKey=POC_ESQL
sonar.qualitygate.wait=true
sonar.sources=.
sonar.inclusions= PLM2PDH_DTCPOM.esql,PLM2PDH_DTCPOM_ai_autofix.esql
sonar.host.url=http://10.11.12.149:9000
sonar.sourceEncoding=UTF-8
sonar.iib.trace.directory=target/iibTrace